queue: Hosted Linux Preview
variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: Build
  workingDirectory: $(system.defaultWorkingDirectory)/ContentManager
- script: mkdir -p Coverage && dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=./Coverage/ > Coverage/coverage.output
  displayName: Test
  workingDirectory: $(system.defaultWorkingDirectory)/ContentManager/ContentManager.Test
- script: dotnet reportgenerator -reports:Coverage/coverage.cobertura.xml -targetdir:Coverage/Report -reporttypes:HTMLInline
  displayName: Reports
  workingDirectory: $(system.defaultWorkingDirectory)/ContentManager/ContentManager.Test
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation:  $(system.defaultWorkingDirectory)/ContentManager/ContentManager.Test/Coverage/coverage.cobertura.xml
    reportDirectory: $(system.defaultWorkingDirectory)/ContentManager/ContentManager.Test/Coverage/Report
- script: node checkCoverage.js
  displayName: Coverage Threshold
  workingDirectory: $(system.defaultWorkingDirectory)/ContentManager/ContentManager.Test/scripts
