thumbnailDirectory: defaultThumbnails
authors:
  - name: Claudio Rodriguez
    display_name: claudiordgz
    email: claudio.rdgz@gmail.com
    web: https://www.claudiordgz.com
    twitter: claudiordgz
    github: claudiordgz
credits:
  - id: gorkhs
    name: Pujol Cristophe
    twitter: @gorkhs
    pixabay: gorkhs
# default thumbnails to be used
# when no thumbnail was defined
thumbnails:
  -	name: gorkhs-pixabay-cat
    path: pixabay/gorkhs/cat-1740777.svg
    type: img
  -	name: gorkhs-pixabay-head
    path: pixabay/gorkhs/head-1971351.svg
    type: img
  -	name: gorkhs-pixabay-rabbit
    path: pixabay/gorkhs/rabbit-2262101.svg
    type: img
  -	name: gorkhs-pixabay-dog
    path: pixabay/gorkhs/dog-1728494.svg
    type: img
  -	name: gorkhs-pixabay-horse
    path: pixabay/gorkhs/horse-1805300.svg
    type: img
  -	name: gorkhs-pixabay-sheep
    path: pixabay/gorkhs/sheep-1990132.svg
    type: img
  -	name: gorkhs-pixabay-goat
    path: pixabay/gorkhs/goat-1990181.svg
    type: img
  -	name: gorkhs-pixabay-logo
    path: pixabay/gorkhs/logo-2930681_1920.png
    type: img