authors:
  - name: Claudio Rodriguez
    display_name: claudiordgz
    email: claudio.rdgz@gmail.com
    web: https://www.claudiordgz.com
    twitter: claudiordgz
    github: claudiordgz
# default thumbnails to be used
# when no thumbnail was defined
thumbnails:
  - name: 'on thumbnail' 
    path_to_file: 'path to file'
	type: 't' 